package org.mxworld.dra.returndvd.model.view;

import java.sql.Timestamp;

import org.mxworld.dra.common.framework.EntityImpl;
import org.mxworld.dra.common.framework.ViewRowImpl;
import org.mxworld.dra.returndvd.model.view.common.RentalVORow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 02 16:45:34 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RentalVORowImpl extends ViewRowImpl implements RentalVORow {
    private static final String RETURNED_STYLING = "text-decoration:line-through;";

    public static final int ENTITY_RENTAL = 0;
    public static final int ENTITY_INVENTORY = 1;
    public static final int ENTITY_FILM = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RentalId,
        RentalDate,
        InventoryId,
        CustomerId,
        ReturnDate,
        StaffId,
        LastUpdate,
        Title,
        FilmId,
        ReleaseYear,
        Rating,
        TextFormat;
        static AttributesEnum[] vals = null; ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RENTALID = AttributesEnum.RentalId.index();
    public static final int RENTALDATE = AttributesEnum.RentalDate.index();
    public static final int INVENTORYID = AttributesEnum.InventoryId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int STAFFID = AttributesEnum.StaffId.index();
    public static final int LASTUPDATE = AttributesEnum.LastUpdate.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int FILMID = AttributesEnum.FilmId.index();
    public static final int RELEASEYEAR = AttributesEnum.ReleaseYear.index();
    public static final int RATING = AttributesEnum.Rating.index();
    public static final int TEXTFORMAT = AttributesEnum.TextFormat.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RentalVORowImpl() {
    }

    /**
     * Gets Rental entity object.
     * @return the Rental
     */
    public EntityImpl getRental() {
        return (EntityImpl) getEntity(ENTITY_RENTAL);
    }

    /**
     * Gets Inventory entity object.
     * @return the Inventory
     */
    public EntityImpl getInventory() {
        return (EntityImpl) getEntity(ENTITY_INVENTORY);
    }

    /**
     * Gets Film entity object.
     * @return the Film
     */
    public EntityImpl getFilm() {
        return (EntityImpl) getEntity(ENTITY_FILM);
    }

    /**
     * Gets the attribute value for rental_id using the alias name RentalId.
     * @return the rental_id
     */
    public Integer getRentalId() {
        return (Integer) getAttributeInternal(RENTALID);
    }

    /**
     * Sets <code>value</code> as attribute value for rental_id using the alias name RentalId.
     * @param value value to set the rental_id
     */
    public void setRentalId(Integer value) {
        setAttributeInternal(RENTALID, value);
    }

    /**
     * Gets the attribute value for rental_date using the alias name RentalDate.
     * @return the rental_date
     */
    public Timestamp getRentalDate() {
        return (Timestamp) getAttributeInternal(RENTALDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for rental_date using the alias name RentalDate.
     * @param value value to set the rental_date
     */
    public void setRentalDate(Timestamp value) {
        setAttributeInternal(RENTALDATE, value);
    }

    /**
     * Gets the attribute value for inventory_id using the alias name InventoryId.
     * @return the inventory_id
     */
    public Integer getInventoryId() {
        return (Integer) getAttributeInternal(INVENTORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for inventory_id using the alias name InventoryId.
     * @param value value to set the inventory_id
     */
    public void setInventoryId(Integer value) {
        setAttributeInternal(INVENTORYID, value);
    }

    /**
     * Gets the attribute value for customer_id using the alias name CustomerId.
     * @return the customer_id
     */
    public Integer getCustomerId() {
        return (Integer) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for customer_id using the alias name CustomerId.
     * @param value value to set the customer_id
     */
    public void setCustomerId(Integer value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for return_date using the alias name ReturnDate.
     * @return the return_date
     */
    public Timestamp getReturnDate() {
        return (Timestamp) getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for return_date using the alias name ReturnDate.
     * @param value value to set the return_date
     */
    public void setReturnDate(Timestamp value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for staff_id using the alias name StaffId.
     * @return the staff_id
     */
    public Integer getStaffId() {
        return (Integer) getAttributeInternal(STAFFID);
    }

    /**
     * Sets <code>value</code> as attribute value for staff_id using the alias name StaffId.
     * @param value value to set the staff_id
     */
    public void setStaffId(Integer value) {
        setAttributeInternal(STAFFID, value);
    }

    /**
     * Gets the attribute value for last_update using the alias name LastUpdate.
     * @return the last_update
     */
    public Timestamp getLastUpdate() {
        return (Timestamp) getAttributeInternal(LASTUPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for last_update using the alias name LastUpdate.
     * @param value value to set the last_update
     */
    public void setLastUpdate(Timestamp value) {
        setAttributeInternal(LASTUPDATE, value);
    }

    /**
     * Gets the attribute value for title using the alias name Title.
     * @return the title
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for title using the alias name Title.
     * @param value value to set the title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for film_id using the alias name FilmId.
     * @return the film_id
     */
    public Integer getFilmId() {
        return (Integer) getAttributeInternal(FILMID);
    }

    /**
     * Sets <code>value</code> as attribute value for film_id using the alias name FilmId.
     * @param value value to set the film_id
     */
    public void setFilmId(Integer value) {
        setAttributeInternal(FILMID, value);
    }

    /**
     * Gets the attribute value for release_year using the alias name ReleaseYear.
     * @return the release_year
     */
    public Integer getReleaseYear() {
        return (Integer) getAttributeInternal(RELEASEYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for release_year using the alias name ReleaseYear.
     * @param value value to set the release_year
     */
    public void setReleaseYear(Integer value) {
        setAttributeInternal(RELEASEYEAR, value);
    }

    /**
     * Gets the attribute value for rating using the alias name Rating.
     * @return the rating
     */
    public String getRating() {
        return (String) getAttributeInternal(RATING);
    }

    /**
     * Sets <code>value</code> as attribute value for rating using the alias name Rating.
     * @param value value to set the rating
     */
    public void setRating(String value) {
        setAttributeInternal(RATING, value);
    }

    // Custom method called by ADF BC API code

    /**
     * Gets the attribute value for the calculated attribute TextFormat.
     * @return the TextFormat
     */
    public String getTextFormat() {
        //return (String) getAttributeInternal(TEXTFORMAT);

        String retval = null;
        if (getReturnDate() != null) {
            retval = RETURNED_STYLING;
        }
        System.out.println("retval = " + retval);
        return retval;
    }

    public String registerReturn() {
        Timestamp now = new Timestamp(System.currentTimeMillis());
        //setAttribute(RETURNDATE, now);
        setReturnDate(now);
        return null;
    }
}

