package org.mxworld.hra.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 29 21:37:53 EDT 2014
// ---------------------------------------------------------------------
public interface AllEmployees extends ViewObject {
    void queryEmployeeById(Integer id);
}

