package org.mxworld.hra.model.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 29 18:12:33 EDT 2014
// ---------------------------------------------------------------------
public interface AllEmployeesRow extends Row {
    void defineDefaultImage(Integer newDefaultImageId);
}

