package org.mxworld.hra.model.vo.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import org.mxworld.hra.model.vo.common.AllEmployees;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 29 21:37:54 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllEmployeesClient extends ViewUsageImpl implements AllEmployees {
    /**
     * This is the default constructor (do not remove).
     */
    public AllEmployeesClient() {
    }

    public void queryEmployeeById(Integer id) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "queryEmployeeById", new String[] {
                                                                         "java.lang.Integer" }, new Object[] { id });
        return;
    }
}

