package org.mxworld.hra.model.vo.client;

import oracle.jbo.client.remote.RowImpl;

import org.mxworld.hra.model.vo.common.AllEmployeesRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 29 18:12:34 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllEmployeesRowClient extends RowImpl implements AllEmployeesRow {
    /**
     * This is the default constructor (do not remove).
     */
    public AllEmployeesRowClient() {
    }

    public void defineDefaultImage(Integer newDefaultImageId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "defineDefaultImage", new String[] {
                                                                         "java.lang.Integer" }, new Object[] {
                                                                         newDefaultImageId });
        return;
    }
}

