package com.dmcsol.xdm.model.entity;

import com.dmcsol.xdm.common.framework.EntityImpl;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 28 11:53:50 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XdmTasksImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TaskId,
        ElemKey,
        ProgId,
        StartDate,
        StartWhere,
        Text,
        EndDate,
        EndWhere,
        Pax,
        Remarks,
        FlightNo,
        PersId,
        CxlYn,
        XdmElements,
        XdmPersons,
        XdmProgrammes;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int ELEMKEY = AttributesEnum.ElemKey.index();
    public static final int PROGID = AttributesEnum.ProgId.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int STARTWHERE = AttributesEnum.StartWhere.index();
    public static final int TEXT = AttributesEnum.Text.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ENDWHERE = AttributesEnum.EndWhere.index();
    public static final int PAX = AttributesEnum.Pax.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int FLIGHTNO = AttributesEnum.FlightNo.index();
    public static final int PERSID = AttributesEnum.PersId.index();
    public static final int CXLYN = AttributesEnum.CxlYn.index();
    public static final int XDMELEMENTS = AttributesEnum.XdmElements.index();
    public static final int XDMPERSONS = AttributesEnum.XdmPersons.index();
    public static final int XDMPROGRAMMES = AttributesEnum.XdmProgrammes.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XdmTasksImpl() {
    }

    /**
     * Gets the attribute value for TaskId, using the alias name TaskId.
     * @return the value of TaskId
     */
    public DBSequence getTaskId() {
        return (DBSequence) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaskId.
     * @param value value to set the TaskId
     */
    public void setTaskId(DBSequence value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for ElemKey, using the alias name ElemKey.
     * @return the value of ElemKey
     */
    public String getElemKey() {
        return (String) getAttributeInternal(ELEMKEY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ElemKey.
     * @param value value to set the ElemKey
     */
    public void setElemKey(String value) {
        setAttributeInternal(ELEMKEY, value);
    }

    /**
     * Gets the attribute value for ProgId, using the alias name ProgId.
     * @return the value of ProgId
     */
    public Long getProgId() {
        return (Long) getAttributeInternal(PROGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProgId.
     * @param value value to set the ProgId
     */
    public void setProgId(Long value) {
        setAttributeInternal(PROGID, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for StartWhere, using the alias name StartWhere.
     * @return the value of StartWhere
     */
    public String getStartWhere() {
        return (String) getAttributeInternal(STARTWHERE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartWhere.
     * @param value value to set the StartWhere
     */
    public void setStartWhere(String value) {
        setAttributeInternal(STARTWHERE, value);
    }

    /**
     * Gets the attribute value for Text, using the alias name Text.
     * @return the value of Text
     */
    public String getText() {
        return (String) getAttributeInternal(TEXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Text.
     * @param value value to set the Text
     */
    public void setText(String value) {
        setAttributeInternal(TEXT, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the value of EndDate
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for EndWhere, using the alias name EndWhere.
     * @return the value of EndWhere
     */
    public String getEndWhere() {
        return (String) getAttributeInternal(ENDWHERE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndWhere.
     * @param value value to set the EndWhere
     */
    public void setEndWhere(String value) {
        setAttributeInternal(ENDWHERE, value);
    }

    /**
     * Gets the attribute value for Pax, using the alias name Pax.
     * @return the value of Pax
     */
    public Integer getPax() {
        return (Integer) getAttributeInternal(PAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pax.
     * @param value value to set the Pax
     */
    public void setPax(Integer value) {
        setAttributeInternal(PAX, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for FlightNo, using the alias name FlightNo.
     * @return the value of FlightNo
     */
    public String getFlightNo() {
        return (String) getAttributeInternal(FLIGHTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlightNo.
     * @param value value to set the FlightNo
     */
    public void setFlightNo(String value) {
        setAttributeInternal(FLIGHTNO, value);
    }

    /**
     * Gets the attribute value for PersId, using the alias name PersId.
     * @return the value of PersId
     */
    public Long getPersId() {
        return (Long) getAttributeInternal(PERSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersId.
     * @param value value to set the PersId
     */
    public void setPersId(Long value) {
        setAttributeInternal(PERSID, value);
    }

    /**
     * Gets the attribute value for CxlYn, using the alias name CxlYn.
     * @return the value of CxlYn
     */
    public String getCxlYn() {
        return (String) getAttributeInternal(CXLYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for CxlYn.
     * @param value value to set the CxlYn
     */
    public void setCxlYn(String value) {
        setAttributeInternal(CXLYN, value);
    }

    /**
     * @return the associated entity com.dmcsol.xdm.common.framework.EntityImpl.
     */
    public EntityImpl getXdmElements() {
        return (EntityImpl) getAttributeInternal(XDMELEMENTS);
    }

    /**
     * Sets <code>value</code> as the associated entity com.dmcsol.xdm.common.framework.EntityImpl.
     */
    public void setXdmElements(EntityImpl value) {
        setAttributeInternal(XDMELEMENTS, value);
    }

    /**
     * @return the associated entity com.dmcsol.xdm.common.framework.EntityImpl.
     */
    public EntityImpl getXdmPersons() {
        return (EntityImpl) getAttributeInternal(XDMPERSONS);
    }

    /**
     * Sets <code>value</code> as the associated entity com.dmcsol.xdm.common.framework.EntityImpl.
     */
    public void setXdmPersons(EntityImpl value) {
        setAttributeInternal(XDMPERSONS, value);
    }

    /**
     * @return the associated entity com.dmcsol.xdm.common.framework.EntityImpl.
     */
    public EntityImpl getXdmProgrammes() {
        return (EntityImpl) getAttributeInternal(XDMPROGRAMMES);
    }

    /**
     * Sets <code>value</code> as the associated entity com.dmcsol.xdm.common.framework.EntityImpl.
     */
    public void setXdmProgrammes(EntityImpl value) {
        setAttributeInternal(XDMPROGRAMMES, value);
    }

    /**
     * @param taskId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence taskId) {
        return new Key(new Object[] { taskId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.dmcsol.xdm.model.entity.XdmTasks");
    }

    /**
     * Add entity remove logic in this method.
     * MX02282014: HOW TO implement logic delete:
     * 1) Add setCxlYn("Y") call in remove() method
     * 2) Change DML_DELETE to DML_UPDATE in doDML() method (see code change in that method)
     */
    public void remove() {
        setCxlYn("Y");
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_DELETE) {
            super.doDML(DML_UPDATE, e);
        } else {
            super.doDML(operation, e);
        }
        
    }
}

