package org.mxworld.hra.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 27 21:36:23 EDT 2014
// ---------------------------------------------------------------------
public interface HraService extends ApplicationModule {
    void createNewImageForEmployee(Integer employeeId, String imageName);
}

