package org.mxworld.dra.returndvd.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 02 16:49:35 EST 2014
// ---------------------------------------------------------------------
public interface RentalVORow extends Row {
    String registerReturn();
}

